---
version: '3.5'
services:
  haproxy:
    build: .
    ports:
      - 6380:6380
    links:
      - redis_1
      - redis_2
      - redis_3
  redis_0:
    image: redis:3.2.6
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 7000:6379
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
  redis_1:
    image: redis:3.2.6
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf 
    ports:
      - 7001:6379
    links:
      - redis_0:redis-master
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
  redis_2:
    image: redis:3.2.6
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf 
    ports:
      - 7002:6379
    links:
      - redis_0:redis-master
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
  redis_3:
    image: redis:3.2.6
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf 
    ports:
      - 7003:6379
    links:
      - redis_0:redis-master
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf


